export const linksData = [
    {
      section: "Social Media and Messaging",
      data: [
        {
          lnk_id: 1,
          lnk_name: "Facebook",
          //   lnk_image: "facebook.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/facebook.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.facebook.com/",
        },
        {
          lnk_id: 2,
          lnk_name: "Instagram",
          // lnk_image: "instagram.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/instagram.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.instagram.com/",
        },
        {
          lnk_id: 3,
          lnk_name: "Twitter",
          // lnk_image: "twitter.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/twitter.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.twitter.com/",
        },
        {
          lnk_id: 4,
          lnk_name: "Snapchat",
          // lnk_image: "snapchat.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/snapchat.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.snapchat.com/add/",
        },
        {
          lnk_id: 5,
          lnk_name: "Tiktok",
          // lnk_image: "tiktok.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/tiktok.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.tiiktok.com/@",
        },
        {
          lnk_id: 6,
          lnk_name: "Reddit",
          // lnk_image: "reddit.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/reddit.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.reddit.com/user/",
        },
        {
          lnk_id: 7,
          lnk_name: "Pinterest",
          // lnk_image: "pinterest.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/pinterest.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.pinterest.com/",
        },
        {
          lnk_id: 8,
          lnk_name: "Dribble",
          // lnk_image: "dribble.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/dribble.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://www.dribbble.com/",
        },
        {
          lnk_id: 9,
          lnk_name: "Messenger",
          // lnk_image: "messenger.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/messenger.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://m.me/",
        },
        {
          lnk_id: 10,
          lnk_name: "Whatsapp",
          // lnk_image: "whatsapp.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/whatsapp.png"),
          cat_id: 1,
          lnk_active: 1,
          lnk_url: "https://wa.me/",
        },
      ],
    },
    {
      section: "Streaming Platform",
      data: [
        {
          lnk_id: 11,
          lnk_name: "Youtube",
            // lnk_image: "youtube.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/youtube.png"),
          cat_id: 2,
          lnk_active: 1,
          lnk_url: "https://www.youtube.com/channel/",
        },
        {
          lnk_id: 12,
          lnk_name: "Twitch",
          // lnk_image: "twitch.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/twitch.png"),
          cat_id: 2,
          lnk_active: 1,
          lnk_url: "https://www.twitch.com/",
        },
        {
          lnk_id: 13,
          lnk_name: "Vimeo",
          // lnk_image: "vimeo.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/vimeo.png"),
          cat_id: 2,
          lnk_active: 1,
          lnk_url: "https://www.vimeo.com/",
        },
        {
          lnk_id: 14,
          lnk_name: "Spotify",
          // lnk_image: "spotify.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/spotify.png"),
          cat_id: 2,
          lnk_active: 1,
          lnk_url: "https://www.spotify.com/",
        },
      ],
    },
    {
      section: "Podcast",
      data: [
        {
          lnk_id: 15,
          lnk_name: "Anchor",
          //   lnk_image: "anchor.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/anchor.png"),
          cat_id: 3,
          lnk_active: 1,
          lnk_url: "https://www.anchor.com/",
        },
        {
          lnk_id: 16,
          lnk_name: "Apple Podcast",
          // lnk_image: "apple-podcast.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/apple-podcast.png"),
          cat_id: 3,
          lnk_active: 1,
          lnk_url: "https://www.apple.com/apple-podcasts/",
        },
      ],
    },
    {
      section: "Business",
      data: [
        {
          lnk_id: 17,
          lnk_name: "LinkedIn",
          // lnk_image: "linkedin.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/linked.png"),
          cat_id: 4,
          lnk_active: 1,
          lnk_url: "https://www.linkedin.com/",
        },
        {
          lnk_id: 18,
          lnk_name: "Email",
          // lnk_image: "email.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/email.png"),
          cat_id: 4,
          lnk_active: 1,
          lnk_url: "mailto:",
        },
        {
          lnk_id: 19,
          lnk_name: "Calendly",
          // lnk_image: "calendly.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/calendly.png"),
          cat_id: 4,
          lnk_active: 1,
          lnk_url: "https://calendly.com/",
        },
      ],
    },
    {
      section: "Marketplace",
      data: [
        {
          lnk_id: 20,
          lnk_name: "Shopee",
          // lnk_image: "shopee.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/shopee.png"),
          cat_id: 5,
          lnk_active: 1,
          lnk_url: "https://shopee.ph/",
        },
        {
          lnk_id: 21,
          lnk_name: "Lazada",
          // lnk_image: "lazada.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/lazada.png"),
          cat_id: 5,
          lnk_active: 1,
          lnk_url: "https://www.lazada.com.ph/",
        },
        {
          lnk_id: 22,
          lnk_name: "Carousell",
          // lnk_image: "carousell.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/carousell.png"),
          cat_id: 5,
          lnk_active: 1,
          lnk_url: "https://www.carousell.ph/",
        },
      ],
    },
    {
      section: "Payment Services",
      data: [
        {
          lnk_id: 23,
          lnk_name: "GCash",
          // lnk_image: "gcash.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/gcash.png"),
          cat_id: 6,
          lnk_active: 1,
          lnk_url: null,
        },
        {
          lnk_id: 24,
          lnk_name: "PayMaya",
          //   lnk_image: "paymaya.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/paymaya.png"),
          cat_id: 6,
          lnk_active: 1,
          lnk_url: null,
        },
        {
          lnk_id: 25,
          lnk_name: "PayPal",
          //   lnk_image: "paypal.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/paypal.png"),
          cat_id: 6,
          lnk_active: 1,
          lnk_url: null,
        },
        {
          lnk_id: 26,
          lnk_name: "PayMongo",
          //   lnk_image: "paymongo.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/paymongo.png"),
          cat_id: 6,
          lnk_active: 1,
          lnk_url: null,
        },
        {
          lnk_id: 27,
          lnk_name: "Venmo",
          //   lnk_image: "venmo.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/venmo.png"),
          cat_id: 6,
          lnk_active: 1,
          lnk_url: null,
        },
      ],
    },
    {
      section: "Others",
      data: [
        {
          lnk_id: 28,
          lnk_name: "GitHub",
          // lnk_image: "github.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/github.png"),
          cat_id: 7,
          lnk_active: 1,
          lnk_url: "https://github.com/",
        },
        {
          lnk_id: 29,
          lnk_name: "GitLab",
          // lnk_image: "gitlab.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/gitlab.png"),
          cat_id: 7,
          lnk_active: 1,
          lnk_url: "https://gitlab.com/",
        },
      ],
    },
    {
      section: "Embed",
      data: [
        {
          lnk_id: 30,
          lnk_name: "Embed Video",
          // lnk_image: "video.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/video.png"),
          cat_id: 8,
          lnk_active: 1,
          lnk_url: null,
        },
        {
          lnk_id: 31,
          lnk_name: "Files",
          //   lnk_image: "file.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/file.png"),
          cat_id: 8,
          lnk_active: 1,
          lnk_url: null,
        },
      ],
    },
    {
      section: "Custom Links",
      data: [
        {
          lnk_id: 32,
          lnk_name: "Custom Link",
          // lnk_image: "customLink.png",
          lnk_image: require("../../../../../assets/UXMaterials/socialMediaIcons/customLink.png"),
          cat_id: 9,
          lnk_active: 1,
          lnk_url: null,
        },
      ],
    },
  ];